// SPDX-License-Identifier: MIT
pragma solidity 0.8.25;

import {Test} from "forge-std/Test.sol";
import {Groth16Verifier} from "../src/Groth16Verifier.sol";

/// @notice Closes the proof loop on-chain: a real Groth16 proof generated by
///         scripts/prove.js (3 spends folded into the Poseidon chain) must
///         verify against the snarkjs-generated verifier, and any tampered
///         public input must fail.
contract Groth16VerifierTest is Test {
    Groth16Verifier internal verifier;

    // Proof for the sample window in scripts/prove.js:
    //   spends: (0xA1, 100e6), (0xB2, 50e6), (0xA1, 25e6)
    //   whitelist: [0xA1, 0xB2, 0...], perTxLimit: 200e6
    uint256[2] internal pA = [
        0x1a7b24af19e20b7d5a97089eecdeaee8f00c2ffdd5588bdf7e9e9b847155c7cd,
        0x2f8d6df17ef2c31e4c1abd28d98910b6377d66169c366b0313898d366a4ea4fd
    ];
    uint256[2][2] internal pB = [
        [
            0x0966c2af88f81d957063543a12e026eb6f42254035dd2f2f65eb367210559a6e,
            0x102190ffbb1ebca9b8102c01f7417e22a29ed8b007112a87edb512252f5b1503
        ],
        [
            0x15febaa87c4150c35748fe0eb9ecd8fae77885695fc888ff45c7400d003b13c9,
            0x0711124e490871025d34256cd5cc07a9a798d5d1b90d19ce9dbe8c38905f963c
        ]
    ];
    uint256[2] internal pC = [
        0x1ea1e667f401df9deb6296169b5c4f417310ff21fdfd6e9a6380caab77bc0bfa,
        0x0bb67592a19361c314a7393715629602b7009ed85ec93db59ccaead2ac05069b
    ];

    function setUp() public {
        verifier = new Groth16Verifier();
    }

    function _publicSignals() internal pure returns (uint256[12] memory ps) {
        ps[0] = 0; // initialCommitment
        ps[1] = 0x26c940775b3a475a598ceabb052a8fb0c9669be2ae1e5b182a51bc1900848e03; // finalCommitment
        ps[2] = 3; // txCount
        ps[3] = 0xa1; // whitelist[0]
        ps[4] = 0xb2; // whitelist[1]
        // whitelist[2..7] = 0
        ps[11] = 0x0bebc200; // perTxLimit = 200e6
    }

    function test_RealProofVerifiesOnChain() public view {
        assertTrue(verifier.verifyProof(pA, pB, pC, _publicSignals()));
    }

    function test_TamperedPublicInputFails() public view {
        uint256[12] memory ps = _publicSignals();
        ps[2] = 2; // claim fewer txs than were folded
        assertFalse(verifier.verifyProof(pA, pB, pC, ps));

        ps = _publicSignals();
        ps[1] = ps[1] ^ 1; // different final commitment
        assertFalse(verifier.verifyProof(pA, pB, pC, ps));
    }
}
