// SPDX-License-Identifier: MIT
pragma solidity 0.8.25;

import {Test} from "forge-std/Test.sol";
import {VerglasAccount} from "../src/VerglasAccount.sol";
import {ValidationRegistry, IIdentityRegistry} from "../src/ValidationRegistry.sol";
import {VerglasHub} from "../src/VerglasHub.sol";
import {VerglasGate} from "../src/VerglasGate.sol";
import {Groth16Verifier} from "../src/Groth16Verifier.sol";
import {AttestationPacket} from "../src/AttestationPacket.sol";
import {ITeleporterMessenger} from "../src/interfaces/ITeleporterMessenger.sol";
import {MockTeleporterMessenger} from "./mocks/MockTeleporterMessenger.sol";

contract MockToken {
    mapping(address => uint256) public balanceOf;

    function mint(address to, uint256 amount) external {
        balanceOf[to] += amount;
    }

    function transfer(address to, uint256 amount) external returns (bool) {
        if (balanceOf[msg.sender] < amount) return false;
        balanceOf[msg.sender] -= amount;
        balanceOf[to] += amount;
        return true;
    }
}

contract MockIdentity is IIdentityRegistry {
    mapping(uint256 => address) public owners;

    function set(uint256 agentId, address owner) external {
        owners[agentId] = owner;
    }

    function ownerOf(uint256 agentId) external view returns (address) {
        require(owners[agentId] != address(0), "no agent");
        return owners[agentId];
    }
}

/// @notice Full-pipeline test: real VerglasAccount spends reproduce the exact
///         chain the proof in scripts/prove.js was generated for, the Hub binds
///         proof <-> state, verifies on-chain, and stamps the registry.
contract VerglasHubTest is Test {
    VerglasAccount internal account;
    ValidationRegistry internal registry;
    VerglasHub internal hub;
    Groth16Verifier internal verifier;
    MockToken internal token;
    MockIdentity internal identity;
    MockTeleporterMessenger internal teleporter;

    address internal owner = makeAddr("owner");
    address internal agent = makeAddr("agent");
    // Fixed addresses matching scripts/prove.js whitelist publics.
    address internal dexA = address(0xA1);
    address internal dexB = address(0xB2);

    uint256 internal constant AGENT_ID = 1599;
    uint256 internal constant PER_TX = 200e6;
    uint256 internal constant BUDGET = 500e6;
    bytes32 internal constant REQUEST_HASH = keccak256("verglas-window-1");

    // Proof generated by scripts/prove.js for spends (0xA1,100e6)(0xB2,50e6)(0xA1,25e6)
    uint256[2] internal pA = [
        0x1a7b24af19e20b7d5a97089eecdeaee8f00c2ffdd5588bdf7e9e9b847155c7cd,
        0x2f8d6df17ef2c31e4c1abd28d98910b6377d66169c366b0313898d366a4ea4fd
    ];
    uint256[2][2] internal pB = [
        [
            0x0966c2af88f81d957063543a12e026eb6f42254035dd2f2f65eb367210559a6e,
            0x102190ffbb1ebca9b8102c01f7417e22a29ed8b007112a87edb512252f5b1503
        ],
        [
            0x15febaa87c4150c35748fe0eb9ecd8fae77885695fc888ff45c7400d003b13c9,
            0x0711124e490871025d34256cd5cc07a9a798d5d1b90d19ce9dbe8c38905f963c
        ]
    ];
    uint256[2] internal pC = [
        0x1ea1e667f401df9deb6296169b5c4f417310ff21fdfd6e9a6380caab77bc0bfa,
        0x0bb67592a19361c314a7393715629602b7009ed85ec93db59ccaead2ac05069b
    ];
    uint256 internal constant FINAL_COMMITMENT = 0x26c940775b3a475a598ceabb052a8fb0c9669be2ae1e5b182a51bc1900848e03;

    function setUp() public {
        token = new MockToken();
        identity = new MockIdentity();
        verifier = new Groth16Verifier();
        registry = new ValidationRegistry(identity);
        teleporter = new MockTeleporterMessenger();
        hub = new VerglasHub(registry, identity, verifier, ITeleporterMessenger(address(teleporter)));

        address[] memory wl = new address[](2);
        wl[0] = dexA;
        wl[1] = dexB;
        account = new VerglasAccount(owner, agent, address(token), PER_TX, BUDGET, wl);
        token.mint(address(account), 1000e6);

        identity.set(AGENT_ID, owner);
        vm.prank(owner);
        hub.bindAccount(AGENT_ID, address(account));
        vm.prank(owner);
        registry.validationRequest(address(hub), AGENT_ID, "ipfs://request", REQUEST_HASH);
    }

    function _publicSignals() internal pure returns (uint256[12] memory ps) {
        ps[1] = FINAL_COMMITMENT;
        ps[2] = 3;
        ps[3] = uint256(uint160(address(0xA1)));
        ps[4] = uint256(uint160(address(0xB2)));
        ps[11] = PER_TX;
    }

    function _replaySpends() internal {
        vm.startPrank(agent);
        account.spend(dexA, 100e6);
        account.spend(dexB, 50e6);
        account.spend(dexA, 25e6);
        vm.stopPrank();
    }

    function test_ContractChainMatchesCircuitChain() public {
        _replaySpends();
        // The pipeline's keystone: PoseidonT3 on-chain == circomlibjs off-chain.
        assertEq(account.commitment(), FINAL_COMMITMENT);
    }

    function test_FullPipeline_ProofToRegistryStamp() public {
        _replaySpends();
        hub.submitProof(AGENT_ID, REQUEST_HASH, pA, pB, pC, _publicSignals(), "ipfs://response", keccak256("resp"));

        (address validator,, uint8 score,, string memory tag, uint256 lastUpdate) =
            registry.getValidationStatus(REQUEST_HASH);
        assertEq(validator, address(hub));
        assertEq(score, 100);
        assertEq(tag, "verglas:policy-compliance");
        assertGt(lastUpdate, 0);

        (uint256 cpCommitment, uint256 cpCount) = hub.checkpoints(address(account));
        assertEq(cpCommitment, FINAL_COMMITMENT);
        assertEq(cpCount, 3);
    }

    function test_RevertWhen_StateAheadOfProof() public {
        _replaySpends();
        vm.prank(agent);
        account.spend(dexB, 10e6); // a 4th spend the proof does not cover
        vm.expectRevert(VerglasHub.BadFinalCommitment.selector);
        hub.submitProof(AGENT_ID, REQUEST_HASH, pA, pB, pC, _publicSignals(), "ipfs://response", keccak256("resp"));
    }

    function test_RevertWhen_ProofReplayed() public {
        _replaySpends();
        hub.submitProof(AGENT_ID, REQUEST_HASH, pA, pB, pC, _publicSignals(), "ipfs://response", keccak256("resp"));
        // Checkpoint advanced — the same window cannot be proven twice.
        vm.expectRevert(VerglasHub.BadInitialCommitment.selector);
        hub.submitProof(AGENT_ID, REQUEST_HASH, pA, pB, pC, _publicSignals(), "ipfs://response", keccak256("resp"));
    }

    function test_RevertWhen_PolicyMismatch() public {
        _replaySpends();
        uint256[12] memory ps = _publicSignals();
        ps[11] = PER_TX + 1; // claim a different policy than the account enforces
        vm.expectRevert(VerglasHub.BadPolicyBinding.selector);
        hub.submitProof(AGENT_ID, REQUEST_HASH, pA, pB, pC, ps, "ipfs://response", keccak256("resp"));
    }

    function test_RevertWhen_AgentNotBound() public {
        vm.expectRevert(VerglasHub.NoBoundAccount.selector);
        hub.submitProof(777, REQUEST_HASH, pA, pB, pC, _publicSignals(), "ipfs://response", keccak256("resp"));
    }

    function test_RevertWhen_BindByNonOwner() public {
        // agent owns neither the identity nor the account — the identity gate
        // is checked first.
        vm.prank(agent);
        vm.expectRevert(VerglasHub.NotIdentityOwner.selector);
        hub.bindAccount(AGENT_ID, address(account));
    }

    /// @notice An attacker who owns their OWN account must not be able to
    ///         rebind someone else's agentId to it (attestation hijack).
    function test_RevertWhen_HijackBindByForeignAccountOwner() public {
        address attacker = makeAddr("attacker");
        address[] memory wl = new address[](1);
        wl[0] = dexA;
        VerglasAccount attackerAccount = new VerglasAccount(attacker, agent, address(token), PER_TX, BUDGET, wl);

        // attacker owns attackerAccount but NOT AGENT_ID (owner does).
        vm.prank(attacker);
        vm.expectRevert(VerglasHub.NotIdentityOwner.selector);
        hub.bindAccount(AGENT_ID, address(attackerAccount));

        // the legit binding is untouched.
        assertEq(hub.accountOf(AGENT_ID), address(account));
    }

    /// @notice Identity owner who does not own the target account is rejected too.
    function test_RevertWhen_BindIdentityOwnerWrongAccount() public {
        address[] memory wl = new address[](1);
        wl[0] = dexA;
        VerglasAccount otherAccount =
            new VerglasAccount(makeAddr("someoneElse"), agent, address(token), PER_TX, BUDGET, wl);

        vm.prank(owner); // owns AGENT_ID, but not otherAccount
        vm.expectRevert(VerglasHub.NotAccountOwner.selector);
        hub.bindAccount(AGENT_ID, address(otherAccount));
    }

    /// @notice Moving an identity to another vault must not leave the old
    ///         attestation standing: the new vault has its own policy and an
    ///         unproven history, so a stale score-100 must not be carryable.
    function test_RebindingToAnotherVaultInvalidatesTheAttestation() public {
        _replaySpends();
        hub.submitProof(AGENT_ID, REQUEST_HASH, pA, pB, pC, _publicSignals(), "ipfs://response", keccak256("resp"));
        (address attAccount,,,, uint8 score, uint64 issuedAt) = hub.latestAttestation(AGENT_ID);
        assertEq(attAccount, address(account));
        assertEq(score, 100);
        assertGt(issuedAt, 0);

        address[] memory wl = new address[](1);
        wl[0] = dexA;
        VerglasAccount freshVault = new VerglasAccount(owner, agent, address(token), PER_TX, BUDGET, wl);

        vm.expectEmit(address(hub));
        emit VerglasHub.AttestationInvalidated(AGENT_ID, address(account));
        vm.prank(owner);
        hub.bindAccount(AGENT_ID, address(freshVault));

        (,,,,, uint64 issuedAfter) = hub.latestAttestation(AGENT_ID);
        assertEq(issuedAfter, 0, "attestation must be gone after a rebind");
        vm.expectRevert(VerglasHub.NoAttestation.selector);
        hub.carryAttestation(AGENT_ID, keccak256("dispatch"), makeAddr("gate"));
    }

    /// @notice Rebinding to the SAME vault (e.g. restoring a binding after a Hub
    ///         redeploy) must keep the attestation — nothing changed about what
    ///         was proven.
    function test_RebindingToTheSameVaultKeepsTheAttestation() public {
        _replaySpends();
        hub.submitProof(AGENT_ID, REQUEST_HASH, pA, pB, pC, _publicSignals(), "ipfs://response", keccak256("resp"));

        vm.prank(owner);
        hub.bindAccount(AGENT_ID, address(account));

        (,,,, uint8 score, uint64 issuedAt) = hub.latestAttestation(AGENT_ID);
        assertEq(score, 100);
        assertGt(issuedAt, 0);
    }

    function test_Registry_OnlyRequestedValidatorResponds() public {
        vm.prank(owner);
        vm.expectRevert(ValidationRegistry.NotRequestedValidator.selector);
        registry.validationResponse(REQUEST_HASH, 100, "uri", bytes32(0), "tag");
    }

    function test_Registry_RejectsDuplicateRequestAndSelfValidation() public {
        vm.prank(owner);
        vm.expectRevert(ValidationRegistry.RequestAlreadyExists.selector);
        registry.validationRequest(address(hub), AGENT_ID, "uri", REQUEST_HASH);

        vm.prank(owner);
        vm.expectRevert(ValidationRegistry.SelfValidation.selector);
        registry.validationRequest(owner, AGENT_ID, "uri", keccak256("another"));
    }

    function test_Registry_OnlyAgentOwnerRequests() public {
        vm.prank(agent);
        vm.expectRevert(ValidationRegistry.NotAgentOwner.selector);
        registry.validationRequest(address(hub), AGENT_ID, "uri", keccak256("other"));
    }

    function test_RevertWhen_CarryWithoutAttestation() public {
        vm.expectRevert(VerglasHub.NoAttestation.selector);
        hub.carryAttestation(AGENT_ID, keccak256("dispatch"), makeAddr("gate"));
    }

    function test_CarrySendsAttestationPacket() public {
        _replaySpends();
        hub.submitProof(AGENT_ID, REQUEST_HASH, pA, pB, pC, _publicSignals(), "ipfs://response", keccak256("resp"));

        bytes32 destChain = keccak256("dispatch");
        address gate = makeAddr("gate");
        hub.carryAttestation(AGENT_ID, destChain, gate);

        assertEq(teleporter.lastDestinationBlockchainID(), destChain);
        assertEq(teleporter.lastDestinationAddress(), gate);
        assertEq(teleporter.lastRequiredGasLimit(), hub.CARRY_GAS_LIMIT());

        AttestationPacket memory packet = abi.decode(teleporter.lastMessage(), (AttestationPacket));
        assertEq(packet.agentId, AGENT_ID);
        assertEq(packet.account, address(account), "packet must name the vault it proved");
        assertEq(packet.requestHash, REQUEST_HASH);
        assertEq(packet.finalCommitment, FINAL_COMMITMENT);
        assertEq(packet.txCount, 3);
        assertEq(packet.score, 100);
        assertEq(packet.issuedAt, uint64(block.timestamp));
    }

    /// @notice The M1 end-to-end story in one test: prove on C-Chain, stamp the
    ///         registry, carry the attestation over ICM, pass the gate on the
    ///         second chain.
    function test_FullPipeline_ProofToGateClearance() public {
        _replaySpends();
        hub.submitProof(AGENT_ID, REQUEST_HASH, pA, pB, pC, _publicSignals(), "ipfs://response", keccak256("resp"));

        bytes32 hubChain = keccak256("c-chain");
        VerglasGate gate = new VerglasGate(address(teleporter), hubChain, address(hub), 100, 7 days);

        hub.carryAttestation(AGENT_ID, keccak256("dispatch"), address(gate));
        teleporter.deliverLast(address(gate), hubChain, address(hub));

        assertTrue(gate.isCleared(AGENT_ID));
        vm.warp(block.timestamp + 7 days + 1);
        assertFalse(gate.isCleared(AGENT_ID));
    }
}
